lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-slate
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
relative_links:
  enabled:     true
  collections: false
readme_index:
  with_frontmatter: true


title: Joe Muro
description: Joe Muro's project

plugins:
  - jekyll-readme-index

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
